#!/usr/bin/env ruby

# Compile less stylesheets using Less and put them in public/stylesheets
require 'rubygems'
require 'less'
require 'fileutils'

root = File.expand_path('../..', __FILE__)

stylesheets_path_orig = File.join(root, 'app', 'stylesheets')
stylesheets_path_dest = File.join(root, 'public', 'stylesheets')

Dir[File.join(stylesheets_path_orig, '*')].each do |stylesheet|
  if stylesheet =~ /\.le?ss$/
    engine = File.open(stylesheet) { |f| Less::Engine.new(f) }
    destination = File.join(stylesheets_path_dest, File.basename(stylesheet).gsub(/\.le?ss$/, '.css'))
    File.open(destination, "w") { |f| f.puts(engine.to_css) }
  else
    FileUtils.cp(stylesheet, stylesheets_path_dest)
  end
end

puts "Stylesheets generated into #{stylesheets_path_dest}"
